spring.application.name=DAO

# DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/dao
spring.datasource.username=postgres
spring.datasource.password=Serebro11!!
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway (??????? ??? ???????? ??)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-version=0 # ???? ?? ??????
spring.flyway.baseline-description=Initial Baseline
spring.sql.init.mode=never

