spring.application.name=DAO

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/dao}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Serebro11!!}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never

